import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Database } from "@/lib/supabase/database.types";
import { cn } from "@/lib/utils";

type Props = {
  logs: Database["public"]["Tables"]["taskLogs"]["Row"][];
};

export default function TaskLogs({ logs }: Props) {
  if (logs.length === 0) return null;

  return (
    <Card className="overflow-hidden">
      <CardHeader className="bg-muted dark:bg-background rounded-t-lg py-4">
        <CardTitle className="text-base">Logs</CardTitle>
        <CardDescription>Logs generated by this task</CardDescription>
      </CardHeader>
      <CardContent className="px-4 py-2">
        <Table>
          <TableHeader className="text-muted-foreground">
            <TableRow>
              <TableHead>Time</TableHead>
              <TableHead>Level</TableHead>
              <TableHead>Message</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {logs.map((log) => (
              <TableRow key={log.taskLogId}>
                <TableCell width={220} className="text-muted-foreground">
                  {log.timestamp.split("+")[0]}
                </TableCell>
                <TableCell
                  width={80}
                  className={cn("font-bold", {
                    "text-destructive": log.logLevel === "ERROR",
                    "text-primary dark:text-blue-500": log.logLevel === "INFO",
                  })}
                >
                  {log.logLevel}
                </TableCell>
                <TableCell>{log.message}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}
